package com.platforma.backend.lookup;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class LookupSeeder {

    private final LookupService lookupService;

    @PostConstruct
    public void seed() {
        // Expert Areas (din doc) :contentReference[oaicite:2]{index=2}
        List<String> expertAreas = List.of(
                "Natural & Physical Sciences",
                "Mathematics",
                "Statistics & Probability",
                "Physics",
                "Chemistry",
                "Earth Sciences",
                "Atmospheric & Climate Science",
                "Oceanography",
                "Astronomy & Astrophysics",
                "Materials Science",
                "Environmental Science",
                "Life Sciences & Biotechnology",
                "Molecular Biology",
                "Cell Biology",
                "Genetics & Genomics",
                "Bioinformatics & Computational Biology",
                "Microbiology",
                "Biochemistry",
                "Neuroscience",
                "Physiology",
                "Ecology & Evolutionary Biology",
                "Biotechnology & Synthetic Biology",
                "Medical & Health Sciences",
                "Clinical Medicine",
                "Public Health",
                "Epidemiology",
                "Health Informatics",
                "Biomedical Engineering",
                "Pharmacology & Toxicology",
                "Immunology",
                "Oncology",
                "Mental Health & Psychiatry",
                "Nursing & Allied Health Sciences",
                "Computer Science & Artificial Intelligence",
                "Artificial Intelligence",
                "Machine Learning",
                "Data Science",
                "Computer Vision",
                "Natural Language Processing",
                "Human–Computer Interaction",
                "Software Engineering",
                "Computer Systems & Networks",
                "Cybersecurity",
                "Robotics & Autonomous Systems",
                "Engineering & Technology",
                "Electrical Engineering",
                "Mechanical Engineering",
                "Civil & Structural Engineering",
                "Chemical Engineering",
                "Industrial & Systems Engineering",
                "Robotics Engineering",
                "Energy Systems Engineering",
                "Nanotechnology",
                "Manufacturing & Materials Engineering",
                "Environmental, Energy & Sustainability",
                "Climate Change Research",
                "Renewable Energy",
                "Energy Systems & Policy",
                "Sustainability Science",
                "Environmental Policy",
                "Conservation Science",
                "Urban & Regional Planning",
                "Water Resources Management",
                "Food & Agricultural Systems",
                "Social Sciences",
                "Economics",
                "Political Science",
                "Sociology",
                "Anthropology",
                "Human Geography",
                "Demography & Population Studies",
                "Criminology",
                "Development Studies",
                "Public Policy",
                "International Relations",
                "Business, Management & Law",
                "Management & Organization Studies",
                "Entrepreneurship & Innovation",
                "Finance & Accounting",
                "Marketing & Consumer Research",
                "Operations & Supply Chain",
                "Organizational Behavior",
                "Information Systems",
                "Law & Legal Studies",
                "Intellectual Property",
                "Corporate Governance",
                "Education & Learning Sciences",
                "Education Research",
                "Learning Sciences",
                "Educational Technology",
                "Curriculum & Instruction",
                "Assessment & Evaluation",
                "Higher Education Studies",
                "STEM Education",
                "Teacher Education",
                "Lifelong Learning",
                "Humanities & Arts",
                "Philosophy",
                "History",
                "Linguistics",
                "Literature",
                "Cultural Studies",
                "Religious Studies",
                "Ethics",
                "Media & Communication Studies",
                "Art History",
                "Digital Humanities",
                "Interdisciplinary & Applied Research",
                "Science & Technology Studies (STS)",
                "Computational Social Science",
                "Digital Health",
                "Human-Centered Design",
                "Cognitive Science",
                "Behavioral Science",
                "Policy & Evidence Synthesis",
                "Innovation Studies",
                "Translational Research"
        );

        // Company Domains (din doc) :contentReference[oaicite:3]{index=3}
        List<String> companyDomains = List.of(
                "Technology & Digital",
                "Software Development & Applications",
                "Artificial Intelligence & Machine Learning",
                "Data Science & Analytics",
                "Cybersecurity",
                "Cloud Computing & IT Infrastructure",
                "Automation & Robotics",
                "Internet of Things (IoT)",
                "Blockchain & Web3",
                "Virtual & Augmented Reality (VR/AR)",
                "Health, Biotech & Life Sciences",
                "Medical Technologies (MedTech)",
                "Digital Health / HealthTech",
                "Biotechnology",
                "Bioinformatics & Biomedical Data",
                "Medical Devices",
                "Clinical Research & Pharmaceuticals",
                "Nutrition & Wellness",
                "Mental Health & Wellbeing",
                "Energy, Environment & Sustainability",
                "Renewable Energy",
                "Energy Efficiency",
                "Environmental Technologies",
                "Sustainability & ESG",
                "Circular Economy",
                "Sustainable Agriculture (AgriTech)",
                "Water & Resource Management",
                "Climate Technologies (ClimateTech)",
                "Engineering & Manufacturing",
                "Mechanical Engineering",
                "Electrical & Electronic Engineering",
                "Industrial Engineering",
                "Advanced Manufacturing",
                "Advanced Materials",
                "Nanotechnology",
                "Industrial Design & Prototyping",
                "Hardware & Embedded Systems",
                "Mobility & Smart Infrastructure",
                "Smart Mobility",
                "Automotive & Electric Vehicles",
                "Logistics & Supply Chain",
                "Smart Cities",
                "Construction & Infrastructure",
                "Drones & Autonomous Systems",
                "Business, Finance & Consulting",
                "Business Consulting",
                "Strategy & Management",
                "FinTech",
                "Financial Analysis",
                "Marketing & Growth",
                "Market Research",
                "Innovation Management",
                "Legal & Intellectual Property",
                "Commerce, Media & Creative Industries",
                "E-commerce & Marketplaces",
                "Retail & Consumer Tech",
                "Digital Media",
                "Advertising & Communications",
                "Design & UX/UI",
                "Gaming & Entertainment",
                "Content Creation & Publishing",
                "Education, Training & Knowledge",
                "Digital Education (EdTech)",
                "Professional Training",
                "Learning Platforms",
                "Research & Development (R&D)",
                "Technology Transfer",
                "Knowledge Management",
                "Social Impact & Public Sector",
                "Social Innovation",
                "Public Policy",
                "Community Development",
                "GovTech",
                "Non-Profit & Social Economy",
                "Impact Assessment & Evaluation",
                "Interdisciplinary & Emerging Technologies",
                "Deep Tech",
                "Applied Research",
                "Human-Centered Design",
                "Behavioral Science (Applied)",
                "Digital Transformation",
                "Cross-disciplinary Solutions"
        );

        expertAreas.forEach(v -> lookupService.upsert(LookupCategory.EXPERT_AREA, v));
        companyDomains.forEach(v -> lookupService.upsert(LookupCategory.COMPANY_DOMAIN, v));
    }
}
